##########################################
##### OrangeFox specific build flags #####
##########################################

# Maintainer
OF_MAINTAINER := PrintHelloPeople

OF_SCREEN_H=2340
OF_STATUS_H=100
OF_STATUS_INDENT_LEFT=48
OF_STATUS_INDENT_RIGHT=48

# Misc
OF_IGNORE_LOGICAL_MOUNT_ERRORS := 1
OF_HIDE_NOTCH := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_FLASHLIGHT_ENABLE := 0

FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1

TARGET_ARCH=arm64

OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
FOX_DISABLE_APP_MANAGER=1
FOX_NO_SAMSUNG_SPECIAL=1
FOX_DELETE_AROMAFM=1
OF_ALLOW_DISABLE_NAVBAR=0
OF_NO_RELOAD_AFTER_DECRYPTION=1
OF_CHECK_OVERWRITE_ATTEMPTS=1
OF_RUN_POST_FORMAT_PROCESS=1
OF_ADVANCED_SECURITY=1
OF_USE_TWRP_SAR_DETECT=1
OF_DONT_PATCH_ON_FRESH_INSTALLATION=1
OF_NO_TREBLE_COMPATIBILITY_CHECK=1

OF_FIX_DECRYPTION_ON_DATA_MEDIA=1
OF_SKIP_ORANGEFOX_PROCESS=1
OF_QUICK_BACKUP_LIST=/boot;/dtbo;/vendor_boot;/vbmeta;vbmeta_system
OF_KEEP_DM_VERITY_FORCED_ENCRYPTION=1
OF_SKIP_DECRYPTED_ADOPTED_STORAGE=1
TARGET_DEVICE_ALT="fogos,fogos_retcn"
OF_TWRP_COMPATIBILITY_MODE=1
FOX_REPLACE_BUSYBOX_PS=1
FOX_REPLACE_TOOLBOX_GETPROP=1
FOX_USE_NANO_EDITOR=1
FOX_USE_BASH_SHELL=1
FOX_ASH_IS_BASH=1
FOX_USE_TAR_BINARY=1
FOX_USE_XZ_UTILS=1
FOX_USE_SED_BINARY=1
OF_ENABLE_LPTOOLS=1
